# -*- coding: utf-8 -*-
"""Copy of hotelreview .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqeMEEWQDLe22-LtXp29suOE_ah8VGn_
"""



"""## 完整改模型"""

!pip install -q sentence-transformers faiss-cpu transformers accelerate torch

import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/hotelLLM/hotel_reviews_2000.csv",
    encoding="utf-8",
    engine="python",
    nrows=50000
)
reviews = df["review_text"].tolist()

from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = embed_model.encode(reviews)

import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(embeddings))

print("Vectors:", index.ntotal)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-large"

tokenizer = AutoTokenizer.from_pretrained(model_name)
llm_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def ask_hotel(question, k=5):

    # 1 找相關評論
    query_vector = embed_model.encode([question])

    distances, indices = index.search(query_vector, k)

    retrieved_reviews = [reviews[i] for i in indices[0]]

    context = "\n".join(retrieved_reviews)

    # 2 Prompt
    prompt = f"""
You are a hotel review assistant.

Based on the following hotel reviews:

{context}

Answer the question:
{question}

Also provide:

Pros:
Cons:
"""

    # 3 LLM生成
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=150
    )

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return answer

ask_hotel("Is this hotel quiet?")

"""# Gradio"""

!pip install -q gradio

import gradio as gr

def hotel_demo(question):

    answer = ask_hotel(question)

    return answer

demo = gr.Interface(
    fn=hotel_demo,
    inputs=gr.Textbox(
        label="Ask about the hotel",
        placeholder="Example: Is the hotel quiet?"
    ),
    outputs=gr.Textbox(
        label="AI Answer"
    ),
    title="Hotel Review AI Assistant",
    description="Ask questions about hotel reviews using AI."
)

demo.launch()